<?php
$news = $this->getNewsCollection();
$newsViewUrl = Mage::getUrl('news/index/view');
//echo Mage::helper('customer')->getCustomer()->getId();
//print_r(Mage::helper('customer')->getCustomer()->getData());

?>
<div class="col-main111">
<form action="<?php echo Mage::getUrl('news/index/save') ?>" method="post">
	<?php if ($this->helper('customer')->isLoggedIn()): echo 
	'<h4>Имя:</h4>'; endif;?><p id="welcomee" ><?php echo Mage::getSingleton('customer/session')->getCustomer()->getName();?></p>
	<?php if ($this->helper('customer')->isLoggedIn()): echo 
	'<p>Отзыв<Br>
	<textarea name="content" cols="40" rows="3"></textarea></p>
	<input name="button" type="submit" value="Добавить запись"></p>'; else: echo 'Войдите на сайт чтобы оставить отзыв!!!!'; endif;?>
</form>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<div class="page-title">
    <h1><?php echo $this->__('Отзыв') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($collection->getSize()): ?>
<table class="data-table" id="my-custom-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('NANE') ?></th>
            <th><?php echo $this->__('CONTENT') ?></th>
            <th><span class="nobr"><?php echo $this->__('CREATED') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $_obj): ?>
        <tr>
           
			<td><span class="nobr"><?php echo $_obj->getTitle(); ?></span></td>
			<td><span class="nobr"><?php echo $_obj->getcontent(); ?></span></td>
            <td><?php echo $this->formatDate($_obj->getCreatedTime()) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-custom-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('The collection is empty.'); ?></p>
<?php endif ?>
